### ISSUE TITLE
前端启用报错

### ISSUE THREAD

**Issue by nondevops** [elliottssu/insight#1]
![image](https://user-images.githubusercontent.com/12181410/78347136-99139200-75d2-11ea-9ab0-8285ec02eb2a.png)
![image](https://user-images.githubusercontent.com/12181410/78347158-a2046380-75d2-11ea-87ca-476d4f52027b.png)
@Elliottssu 看看呢.

**Comment by elliottssu** [comment]
@nondevops 这个是node版本号太低了 报错的版本是node 6.17.1
可以把升级到node最新稳定版
