### ISSUE TITLE
数据库文件在哪？

### ISSUE THREAD

**Issue by Golee520** [elliottssu/insight#10]
小白哈，建了mysql数据库，也改了配置了，但数据库文件在哪？怎么还原数据表呢？

**Comment by elliottssu** [comment]
@Golee520 这里喔 一个是本地环境 一个是生产环境
 insight-back-end/config/config.default.ts
 insight-back-end/config/config.prod.ts
 
 这个用自己的数据库就可以，新建一个自己的数据库  会自动创建所需要的表

**Comment by weituotian** [comment]
@elliottssu 

`npm run dev ` 是对应 insight-back-end/config/config.default.ts
然后
`npm run start` 是对应 insight-back-end/config/config.prod.ts 吗？

**Comment by elliottssu** [comment]
@weituotian 是的 可以这样理解
