### ISSUE TITLE
定时任务执行的时间有问题

### ISSUE THREAD

**Issue by gyc-lan** [elliottssu/insight#3]
<img width="566" alt="截屏2020-04-27 17 13 08" src="https://user-images.githubusercontent.com/35367568/80355286-75c6c480-88aa-11ea-8042-1ab07394e9a2.png">
定时是每天早上9:00
但是实际在下午15:00会有一次推送
我试了另一个定时任务，也是会隔8小时又一次推送
定时的时候打开了“工作日（智能跳过节假日）“这个开关

**Comment by elliottssu** [comment]
@gyc-lan 从目前的机器人来看 选择工作日每天都可以正常运行。
您能否提供一些其他信息，
比如是在测试网上添加的吗（如果是自己部署的，可以提供一下服务器基本信息）？
有没有可能机器人在其他地方也在运行（尝试更换一个机器人）
等

定时器会转化为标准的cron表达式，按理说不会出现每隔几个小时触发一下

**Comment by iamwlb** [comment]
我这边也有类似的问题，明明设定的是18:15分发送信息，可是却在早晨6:15发送。

**Comment by elliottssu** [comment]
@iamwlb 您好 初步认为是因为系统时区的问题，您那边可以查看有问题的机器是否是 北京东8区时区吗？
