### ISSUE TITLE
指定人发送通过用户名发送

### ISSUE THREAD

**Issue by nondevops** [elliottssu/insight#5]
当前指定人发布只能通过手机号码,常见的@方式还有指定用户名,如果方便的话,还请支持下,谢谢

**Comment by elliottssu** [comment]
@nondevops 目前官方文档中不支持用户名，只支持用户ID和手机号，而且用户ID获取方式比较困难，手机号是最好的方式了

**Comment by nondevops** [comment]
@Elliottssu 了解,谢谢
